### ISSUE TITLE
feedback session chapter not to appear in curriculum

### ISSUE THREAD

**Issue by mumacadam** [DecouvreBitcoin/sovereign-university#528]

**Comment by Rogzy-DB** [comment]
After verification, we will keep the Review in the curriculum. What we wanted was to rename it from the original very long name to something shorter like "Course Ratings & Feedback" . 

Since this should always be the 3rd last chapter, we can keep it. After it will be the final exam, and then the conclusion chpater. 

Idealy the data team will include those 3 chapter under a #conclusion section. 

So we keep it in the curriculum to make it simplier.
