### ISSUE TITLE
BUG - Can we weighden the card so it fill up the screen starting from the left

### ISSUE THREAD

**Issue by Flashmaxi** [DecouvreBitcoin/sovereign-university#568]

**Comment by Flashmaxi** [comment]
![Image](https://github.com/user-attachments/assets/5d0117fc-f6a0-4164-8c1a-0d75e78c7858)

**Comment by Flashmaxi** [comment]
![Image](https://github.com/user-attachments/assets/c6da1331-e989-46c3-b894-23901c960eae)

**Comment by Rogzy-DB** [comment]
Please make the invisible bounderay going all the way. 

now it's just align on the left but if we clic on the right nothing happen since it's empty. 

I just want the card to be fill up the screen from right to left, but alogned left. If not enought texte, it's just blank on the right but can be clic

**Comment by Flashmaxi** [comment]
Done, will be merged later.
